ALTER TABLE telegram_inbox ADD COLUMN actor_id uuid;
ALTER TABLE telegram_inbox ADD COLUMN arrival bigint GENERATED BY DEFAULT AS IDENTITY;
-- Telegram may reset update IDs after a quiet week. Runtime ordering uses local
-- arrival order, while update IDs remain only the provider deduplication key.
WITH ordered AS (
    SELECT bot_id,update_id,row_number() OVER(ORDER BY received_at,update_id) AS ordinal
    FROM telegram_inbox
)
UPDATE telegram_inbox SET arrival=ordered.ordinal FROM ordered
WHERE telegram_inbox.bot_id=ordered.bot_id AND telegram_inbox.update_id=ordered.update_id;
SELECT setval(pg_get_serial_sequence('telegram_inbox','arrival'),GREATEST(COALESCE((SELECT max(arrival) FROM telegram_inbox),0),1),EXISTS(SELECT 1 FROM telegram_inbox));
CREATE UNIQUE INDEX inbox_arrival ON telegram_inbox(arrival);
ALTER TABLE telegram_inbox ADD COLUMN routed boolean NOT NULL DEFAULT false;
ALTER TABLE telegram_inbox ADD COLUMN protective boolean NOT NULL DEFAULT true;
ALTER TABLE telegram_inbox ADD COLUMN quarantined_at timestamptz;
ALTER TABLE telegram_inbox ADD COLUMN next_attempt_at timestamptz NOT NULL DEFAULT clock_timestamp();
ALTER TABLE telegram_inbox ADD COLUMN lease_until timestamptz;
ALTER TABLE telegram_inbox ADD COLUMN lease_token uuid;
ALTER TABLE telegram_inbox ADD COLUMN last_error text;
ALTER TABLE telegram_inbox ADD COLUMN coalesce_key text;
ALTER TABLE telegram_inbox ADD COLUMN recovery_profile uuid;
ALTER TABLE telegram_inbox ADD COLUMN recovery_selector uuid;
CREATE TABLE telegram_inbox_scopes (
    bot_id bigint NOT NULL,
    update_id bigint NOT NULL,
    plan_id uuid NOT NULL,
    protective boolean NOT NULL DEFAULT true,
    PRIMARY KEY (bot_id,update_id,plan_id),
    FOREIGN KEY(bot_id,update_id) REFERENCES telegram_inbox(bot_id,update_id) ON DELETE CASCADE
);
CREATE INDEX inbox_scope_barrier ON telegram_inbox_scopes(plan_id,bot_id,update_id);
CREATE INDEX inbox_actor_order ON telegram_inbox(actor_id,arrival) WHERE processed_at IS NULL AND quarantined_at IS NULL;
CREATE INDEX inbox_retry_due ON telegram_inbox(priority DESC,next_attempt_at,update_id) WHERE processed_at IS NULL AND quarantined_at IS NULL;
CREATE TABLE runtime_health (
    singleton boolean PRIMARY KEY DEFAULT true CHECK(singleton),
    integrity_failure boolean NOT NULL DEFAULT false
);
INSERT INTO runtime_health(singleton) VALUES(true);
CREATE TABLE resource_reservations (
    resource text NOT NULL,
    reservation_id uuid NOT NULL,
    amount bigint NOT NULL CHECK(amount>=0),
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    PRIMARY KEY(resource,reservation_id)
);
CREATE TABLE recovery_account_grants (
    selector uuid PRIMARY KEY,
    profile_id uuid NOT NULL,
    account_id uuid NOT NULL,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
-- Existing objects count against the same budget, including copies awaiting GC.
INSERT INTO resource_reservations(resource,reservation_id,amount)
SELECT 'blob_bytes',id,COALESCE((data->>'size')::bigint,0) FROM file_objects WHERE state<>'deleted';
INSERT INTO resource_reservations(resource,reservation_id,amount)
SELECT 'payload/drafts',id,octet_length((data->'payload')::text) FROM drafts
UNION ALL SELECT 'payload/secret_versions',id,octet_length((data->'payload')::text) FROM secret_versions;
CREATE TABLE runtime_plan_schedule (
    plan_id uuid PRIMARY KEY,
    next_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_error text,
    failures integer NOT NULL DEFAULT 0
);
INSERT INTO runtime_plan_schedule(plan_id) SELECT id FROM plans WHERE state<>'deleted';
CREATE INDEX runtime_plans_due ON runtime_plan_schedule(next_at,plan_id);
CREATE INDEX accounts_scope_keyset ON accounts(scope_id,id);
CREATE INDEX plans_scope_keyset ON plans(scope_id,id);
CREATE INDEX actions_expiry ON actions(((data->>'expires_at')::bigint),id);
CREATE INDEX jobs_expiry ON outbox(((data->>'expires_at')::bigint),id);
CREATE INDEX secrets_guardian_membership ON secret_versions USING gin ((data#>'{policy,guardians}'));
CREATE INDEX secrets_recipient_membership ON secret_versions USING gin ((data#>'{policy,recipients}'));
CREATE INDEX pending_control_intents ON control_intents(id) WHERE data->>'applied'='false';

CREATE INDEX file_objects_draft ON file_objects ((data->>'draft_id'),id);
CREATE INDEX jobs_download_draft ON outbox ((data#>>'{task,draft_id}'),id) WHERE data#>>'{task,kind}'='download_file';
CREATE INDEX profiles_recovery_selector ON profiles ((data->>'recovery_selector')) WHERE state<>'deleted';
